### ISSUE TITLE
cmake成功后但是还是报不支持relu的错

### ISSUE THREAD

**Issue by w-Bro** [chineseocr/opencv-for-darknet#1]
centos7

`
cv2.error: OpenCV(4.0.0) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:552: error: (-212:Parsing error) Unsupported activation: relu in function 'ReadDarknetFromCfgStream'
`

**Comment by wenlihaoyu** [comment]
先执行 unzip  opencv.4.0.1.zip && \
cp darknet_io.cpp opencv-4.0.1/modules/dnn/src/darknet && \
cp layers_common.cpp opencv-4.0.1/modules/dnn/src/layers && \
cp all_layers.hpp opencv-4.0.1/modules/dnn/include/opencv2/dnn/
再进行安装，详细看README文件。

**Comment by w-Bro** [comment]
@wenlihaoyu 已经做了这一步了。不知道是不是虚拟环境的问题，我将几个配置换成了我自己的路径，但是还是不行。
`cmake -D CMAKE_BUILD_TYPE=RELEASE \
     -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D BUILD_opencv_python2=OFF \
    -D BUILD_opencv_python3=ON  \
   -D PYTHON3_EXCUTABLE=/root/miniconda3/envs/darknet-ocr/bin/python \
  -D PYTHON3_INCLUDE_DIR=/root/miniconda3/envs/darknet-ocr/include/python3.6m  \
-D PYTHON3_LIBRARY=/root/miniconda3/envs/darknet-ocr/lib/libpython3.6m.so \
-D PYTHON_NUMPY_PATH=/root/miniconda3/envs/darknet-ocr/lib/python3.6/site-packages/numpy/ .. \
&& make -j2 && make install
`

**Comment by wenlihaoyu** [comment]
你应该之前用pip install方式安装过，先将/root/miniconda3/envs/darknet-ocr目录下的opencv删除掉，然后用命令查找opencv编译生成的cv2.so在什么位置（make install 环境就能看到），然后用ln链接就行。例如mac系统：
rm ~/anaconda3/envs/opencv/lib/python3.6/site-packages/cv2.cpython-36m-darwin.so
ln -s /usr/local/lib/python3.6/site-packages/cv2/python-3.6/cv2.cpython-36m-darwin.so ~/anaconda3/envs/opencv/lib/python3.6/site-packages/cv2.cpython-36m-darwin.so

**Comment by w-Bro** [comment]
刚才弄好了，将opencv-4.0.1/cmake/lib/python3/cv2.cpython-36m-x86_64-linux-gnu.so替换掉了/root/miniconda3/envs/darknet-ocr/lib/python3.6/site-packages/cv2/cv2.cpython-36m-x86_64-linux-gnu.so
